# Generated by Django 4.1.2 on 2022-10-13 22:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, verbose_name='Год выпуска')),
                ('brand', models.CharField(max_length=255, verbose_name='Марка')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('vin', models.CharField(max_length=255, unique=True, verbose_name='VIN')),
                ('odometer', models.CharField(max_length=255, verbose_name='Пробег (миль)')),
                ('engine', models.CharField(max_length=255, verbose_name='Объем двигателя')),
                ('gearbox', models.CharField(max_length=255, verbose_name='КПП')),
                ('drive_train', models.CharField(max_length=255, verbose_name='Привод')),
                ('auction_date', models.CharField(max_length=255, verbose_name='Дата аукциона')),
                ('sale_type', models.CharField(max_length=255, verbose_name='Тип продажи')),
                ('damage', models.CharField(max_length=255, verbose_name='Повреждения')),
                ('photo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Фото'), size=None)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
