# Generated by Django 4.1.2 on 2023-04-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_hidden_v2',
            field=models.BooleanField(default=False, verbose_name='Скрыть для API v2'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыть для API v1'),
        ),
    ]
