# Generated by Django 4.2 on 2023-04-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_is_hidden_v2_alter_car_is_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('id',), 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
    ]
