# Generated by Django 4.2 on 2023-04-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterField(
            model_name='car',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Скрыть для API v1'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_hidden_v2',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Скрыть для API v2'),
        ),
    ]
